export enum Events {
    SESSION_UPDATE = "SESSION_UPDATE",
    PLAYERS_UPDATE = "PLAYERS_UPDATE",
    PLAYER_STAT_UPDATE = "PLAYER_STAT_UPDATE",
    PLAYER_SELFIE_UPDATE = "PLAYER_SELFIE_UPDATE",
    PLAYER_REMOVED = "PLAYER_REMOVED",
    CONNECTION_UPDATE = "CONNECTION_UPDATE",
    CONNECT_WITHDRAWN = "CONNECT_WITHDRAWN",
}